apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-bitnami
  project: andrew-naas
spec:
  endpoint: https://charts.bitnami.com/bitnami
  options: {}
  type: Helm
status:
  projects:
  - projectId: k5rw572
    repositoryId: mxzjwj2
  webhookConfig:
    webhookSecret: d6dd47e5167fd1a5890bf858b1aca48cb6663bfae93c75feb872e283cbae1196
    webhookURL: https://console.rafay.dev/v2/config/webhook/repository/mxzjwj2
