apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: default-stable-helm
  project: andrew-naas
spec:
  endpoint: https://charts.helm.sh/stable
  options: {}
  type: Helm
status:
  projects:
  - projectId: k5rw572
    repositoryId: 29eqp3k
  webhookConfig:
    webhookSecret: d6192ec7935951b2b39d6c7cfdb01513626a38dc9e23585cbbb723612a74d0d3
    webhookURL: https://console.rafay.dev/v2/config/webhook/repository/29eqp3k
