apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: naas-git-repo-2
  project: andrew-naas
spec:
  agents:
  - name: naas-gitops-agent
  credentials:
    password: sealed://credentials.password
    username: andrewo-rafay
  endpoint: https://github.com/andrewo-rafay/envmgr/
  options:
    provider: Github
  secret:
    name: file://artifacts/naas-git-repo-2/sealed-secret.yaml
  type: Git
status:
  agents:
  - id: dk3nr8m
    name: naas-gitops-agent
  projects:
  - projectId: k5rw572
    repositoryId: 2wq6gy2
  webhookConfig:
    webhookSecret: 762c75402a3ca1b9af982c7574deddbbbe60c4b707efaca03818f253bf8b64c7
    webhookURL: https://console.rafay.dev/v2/config/webhook/repository/2wq6gy2
