apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: naas-repo-andrew-naas
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCFgiLqu+0DG6VsIHYwE3R7SK1VaiHU0Wkd4gHXdC/rB+hujvSAymYZLJ/htCyNJY0ZN21PcITK6+lsdx9LqA4PIFFgLFzqJztdsLurkUHC8XDABIRjF9L43iFQn0v2+d2z+f9wI23IyEsbkOnia+DzypVtssn/zw36J/vBxl+QRrYHbNWWcC3bpegQx5eLA8CtG7bzQVe0b8r6b+7xTwQjbwg12OzQrdLO37eP0lM7YJDbRX3a85k6+HJbUT8GSasIvjfIu2alqF4HIofP3ngLQFKKPmMm0ryaOMyZp4gaaMpukaQzQK9rHwLTxSmXkBK8iGhLSt/ROSf91sV8vf3Zo75cF5pCDodWqk6sSOG9Nj1Z5zXbujQezOl0yihry3DUVXHrNbUzEP0U/0f7pVnQk2IF7shSovs=
  template:
    metadata:
      creationTimestamp: null
      name: naas-repo-andrew-naas
      namespace: default

