apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: naas-repo-andrew-naas
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBjOz3I534tpGREXRNF648KAIamGzoc50dWOYRx8rPqEGEA9+DDM9tF7dMRPJ/KXjx+pOtV/HEERvX61YKObV9abFB5e3QOgjy0Ay9QqOyfKvsb44ctpjNomcTZz0HP8hUnlab+1Y1YDQ4DGQjZtLku4fxom+pKCeVhTf01DsnikyFjoVHO87fIKDb3Qx2eJvcadQfRvD35GBU5mKw2raVa0A8l0WNe6P0E/yjz+MIz8ke+SfStJ+G8+F0903jTM3vuSaCfuN39QhXpK+AHrZdmmnMJvCOgkl/4uQgMuF06IxOKsLNowHQ/obBjftymVmxob5F4+aN5Hiqlbewr5s/FNoGFtu8BRImuMDOsTxucZ6CXmSqWya92HhrclrJRHW8CvsEXNg7WhJK/Ryny2FahEWfvyAXqshk=
  template:
    metadata:
      creationTimestamp: null
      name: naas-repo-andrew-naas
      namespace: default

