apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: naas-repo-andrew-naas
  namespace: default
spec:
  encryptedData:
    credentials.password: AQDDUgJ/P3ftl/4NzhLpRWmQeWGhMbEfY5ZmkhsWwUgvNOHe2ah6tro1r7ze5/NfHa5ETY1CEuYOQj0az0oGW4FZASxPZghsPKVttRJaVu+VlJRww3+1R+4JA9PQ+CBYf4Nuga2TQAjJ1+hEZvcrj/FN/IRr4vxk58PHZRDm4HC1gA19ypFJmEp17nFhDtpnGXXMlYdt0lVe7dvIzj71N26Jy+ynNqD2iQPRdDiDJiqE0ncmZBj+5CqimH/EjLvU6Ox69F9FP9KCjG+Qx37uR8DekJHbwz2E1r7D/HOOsoUmVobuaIydlG1/4DXwTiSvKL1mPAHHlZ07ClUHC6Hduhg57/15ZY70Q2m/zbUMyxAVBVPi/730dNPdtsu/Qd1hd/UVnkQy4jUmnpIhPq/tLY9jrVdLqZpKsQM=
  template:
    metadata:
      creationTimestamp: null
      name: naas-repo-andrew-naas
      namespace: default

