apiVersion: integrations.k8smgmt.io/v3
kind: SecretSealer
metadata:
  name: rafay-sealer-andrew-naas
  project: andrew-naas
revisions:
- cert: |
    -----BEGIN CERTIFICATE-----
    MIIDWDCCAkCgAwIBAgIQSGNiKXOv0nIz8+WcWkIFqDANBgkqhkiG9w0BAQsFADBG
    MUQwQgYDVQQDEztwYXJ0bmVyPXJ4MjhvbWwsb3JnPXgyODdqZ2ssbmFtZT1yYWZh
    eS1zZWFsZXItYW5kcmV3LW5hYXMtMTAeFw0yNDEwMjEyMTIxNTRaFw0zNDA3MjEy
    MTIxNTRaMEYxRDBCBgNVBAMTO3BhcnRuZXI9cngyOG9tbCxvcmc9eDI4N2pnayxu
    YW1lPXJhZmF5LXNlYWxlci1hbmRyZXctbmFhcy0xMIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEAqys2z36HP+qmeif4DQVUOc5F/GePpgIcoraghRtDeVMc
    LjyVXTS4bhqgd2jpCd++eAe0z3YRH7O+8lHtVLXbjTNXTbUIBichkREn1sly9LNa
    FoYV6d9riqpYO3an8CZf3s9Z+YG+L6QpMzzm/IAYiv/0NtQP9jXZKms9CgWSJRNr
    WB2eaDNzTXvJe8+beQGRS0leDalGkyXLZxSI7/wBqCXY14PD/l+eUy56GJ+Hc4jM
    Kg4v1wJt6So93Jm2jKmdt6VNBKx/s4420FZaeGJZlE7G9jm4qGrTMOi8GMfcWkMM
    cUf5FOb+d9b1Of1dWCE6IOi5fgi+ZW9FyfNU0spyIwIDAQABo0IwQDAOBgNVHQ8B
    Af8EBAMCAAEwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU+bviGF2AchzxR/VF
    0tYpRjRy4aIwDQYJKoZIhvcNAQELBQADggEBAKElHUsrzQ5MqkvSv8En9HPrGC74
    UJE467rVmBgo535K2InCu0E0I7WWn87hBB3JqjxA78CpCAy1Pqt2TRkQpFZXO0JG
    AtlM4djiC9Rv9eaWINGLLMzMf/8HVbOixWPokxIO7/M9ZMhz6te9sMPtHG7ZdoGV
    ieoQUwQrDYNEu599OdkJwN+euMzTCtGb527q5Tff5WW8GC3fIMPOjAgI5isezxn0
    HF4UBnWKu4e8v5jRB5vz+gFkQKU18jGo5QRtd+1uiywUBsKoaPH89MceLlcWpeVJ
    1alnl6Y4JR9i/YVUU2HQ5Pouwl9NP5w7vAXGzC8fqMKh87JDVKUdSW3w+To=
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCrKzbPfoc/6qZ6
    J/gNBVQ5zkX8Z4+mAhyitqCFG0N5UxwuPJVdNLhuGqB3aOkJ3754B7TPdhEfs77y
    Ue1UtduNM1dNtQgGJyGRESfWyXL0s1oWhhXp32uKqlg7dqfwJl/ez1n5gb4vpCkz
    POb8gBiK//Q21A/2Ndkqaz0KBZIlE2tYHZ5oM3NNe8l7z5t5AZFLSV4NqUaTJctn
    FIjv/AGoJdjXg8P+X55TLnoYn4dziMwqDi/XAm3pKj3cmbaMqZ23pU0ErH+zjjbQ
    Vlp4YlmUTsb2ObioatMw6LwYx9xaQwxxR/kU5v531vU5/V1YITog6Ll+CL5lb0XJ
    81TSynIjAgMBAAECggEBAKfMB0FFsmSwLV8XC44IKVc5pVYYV7PP4i6Ihbe20GCB
    XuDctzfV1O7q31/v0nPBiUC1nUS7Y3IGjSuTsOsYFBDJwc4Fp8YQWlGR1dIzTaQg
    pjHqZFUOlqgq8a/pVBySIe2Uq4ly7PRbI6B9FZt2H5kz7T5KiRM+GpQA6KeIaoo4
    ckgf4/Q7lvtkWSHQxakQmJgEUSXKf9cxzkn+5GyN2uK5UUmU0k3SNwlndhI3puu2
    543aR1hKlOzP3Jt9J2lanVywkyH29f+Dtzr9BVJX++p8fE70DgZHv4NUdsaXYkPg
    IyPOafXKTRc9bTytauPFL3FJuVf7P+9iN0v8qCrMZGECgYEA3KAuTqq/uf3U2nGH
    6PWjfgYN9mbyawsfuHup/Eq5daeN8RoPi3jWJuVQ7P9HkjiT/cD5EOzv5MtAVgUn
    TJ8ZmGcpQQy5C/ZoQplQbfjiR33LvXtaXEap5HL7h+Kp0RlTHqTIXH4faLXKap87
    A9fxIxeSLGrIKdL9YdR/b5UBg6kCgYEAxp0FhZSif8zelO4Lg8YBnbQxo0UG9Ylf
    OKfEe2bsJS3h6q1a/X94YHR6X927233kRdQUdFwRCFOJU8HkB4tKzc9+HIz4RhKO
    nuRfL/4/dDiKGkojbGACXrD37igNAIWZhV5S4Wtq0WskFskI4VeDC9h5Jswpw682
    tQzf96svpusCgYEAjF65t8F5pLt0DtvG7hhDQi5V+dy8BhEYyIadu3BLmSjW7Xx4
    QXPLRQoHuBIflk+7EOsTTIqDgx0yPMignWZooYeZPtL6dTr8UMs82gtM5NGLrG3s
    KuOmujvR/z3eb7ReJxQOipKQJ03qkHXo1WQx/vLDRNFXswyTvAe4YOT8BqkCgYAB
    sOiRIJjZmbbzcatrbc4pt5UMnNPYV1kWNGd53YB5OJDJ3Lv/mIw/1f4MvuiQj9vX
    tFyQORB0D7IFoor8fXUfl3qtZ43dmt7X/33H/NQxeyHB44u1qoOapssVngWuUXTj
    K9Bs1utL6SuffgqzUHlvKmKtr+NTJTTECd4GT9DSDQKBgQCxfthE2dxzSuCenKOZ
    kDLbNQjAALr1Ap0kMjyVrtX27LsSie2bC4V3fhKL6OhA+mV7Pk9wDspfRyMfloRw
    cdJ2QKUnoXnuOd8EOeYK4ymDXsjAucugMoqgtPEyQDvqXRlCJ7ypYcMHtS21/jIB
    r6qeV9VEr8LoRmbHJmYp/bLqbA==
    -----END PRIVATE KEY-----
  name: v-1
  status: RevisionStatusActive
spec:
  type: KubeSeal
  version: v-1
