apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: naas-git-repo
  namespace: default
spec:
  encryptedData:
    credentials.password: AQC6tKYkaTY/MrWsBR0D7NSCBUIDYQvbDM+QgOaV5pSq0JMm05NygWq1mmmEma/QMDJjCOQnjVFc4ZSCbUI77DHrEiiNyIa/fUb1UAnzQyCOemKJJ/7WpcGCW/re15unOoFjfUF0DJWCcBmQNSzA142JPblX9KCbgcFFCvEXFrZXrhfSrs2Wi50OiS4BaZvgQuKWOCvJeQmtS4hvUgx/48OP7rU5rsG90fGVDxgUIxJCBQRjz90QLYR8AvZ3l7G3aA0AjyTZEQBbGK8GcoEooMPHlYBFyolsRIcaChR6TT0M0hIzt5eu23QDcOTlakmwLtbiF1+rg2BBAzIM/RemKyJPNUi3Tpzgxcdqd2gVX/qmJ73+zeE9mAsMU5eGB1pt7UgMjc9d0b5eYRxKhuqNMR+Kdz+D
  template:
    metadata:
      creationTimestamp: null
      name: naas-git-repo
      namespace: default

