apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: naas-sync-deploy
  project: andrew-naas
spec:
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        path:
          name: rafay-resources
        repository: naas-repo-andrew-naas
        revision: dev
      systemToGitSync: true
    name: sync
    type: SystemSync
  triggers:
  - config:
      repo:
        paths:
        - name: rafay-resources
        provider: Github
        repository: naas-repo-andrew-naas
        revision: dev
    name: naas-trigger
    type: Webhook
