apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: system-sync-andrew-naas
  project: andrew-naas
spec:
  active: true
  stages:
  - config:
      destinationRepo:
        path:
          name: rafay-resources
        repository: naas-repo-andrew-naas
        revision: dev
      gitToSystemSync: true
      includedResources:
      - name: Environment
      - name: EnvironmentTemplate
      - name: ConfigContext
      - name: Agent
      - name: Repository
      - name: Resource
      - name: ResourceTemplate
      - name: Pipeline
      sourceRepo:
        path:
          name: rafay-resources
        repository: naas-repo-andrew-naas
        revision: dev
      systemToGitSync: true
    name: sync
    type: SystemSync
  triggers:
  - config:
      repo:
        paths:
        - name: rafay-resources
        provider: Github
        repository: naas-repo-andrew-naas
        revision: dev
    name: eaas-trigger
    type: Webhook
