apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: naas-git-repo-2
  namespace: default
spec:
  encryptedData:
    credentials.password: AQC5+M4Ck0N6eVnU07aLDgTPQZavitViI+mwcKkbNs/MeD0rvo+cbwmYOaQuzWCh20FsLBZ/JxH4smHYEWHTzbIfxmAaSTaOGyU4uUuZ04nNVRsRvk5O+BBgOxhXkJ19GMmKki2IknWVX1N5SO+OaWdBRBfAqJUzdh1tKs5uKLg/xgdV1PIlT9YKdBZkqITXPleBXNW8ZkkDOrhUMToKieJb+Kat7ZdT6jCioUrAfLp/veioOVs0obDzJ+fXsd0Z0AzvWzWLTJUf2iynrG/26Q4tKA/CJFmz46d4xxz/fbq+iLG1Dh6rQWVVLvxhk3CmQ+Mt9BNXTyqSoL2tPScQLzAm5/u8lp8xi1osC0i8XDBPLF8ACTs8rhRvwpBHL9304uuoJcNNrXaHORNGqm+D/SzkOtjb6HMF0pA=
  template:
    metadata:
      creationTimestamp: null
      name: naas-git-repo-2
      namespace: default

