apiVersion: eaas.envmgmt.io/v1
kind: ResourceTemplate
metadata:
  name: naas-rs-tmpl-andrew-naas
  project: andrew-naas
spec:
  agents:
  - name: eaas-agent-naas
  contexts:
  - name: rafay-101-naas-andrew-naas
  provider: terraform
  providerOptions:
    terraform:
      backendType: system
      refresh: true
      version: 1.4.6
  repositoryOptions:
    branch: dev
    directoryPath: terraform/naas/101-naas/terraform/namespace
    name: naas-repo-andrew-naas
  variables:
  - name: memory
    options:
      description: Assign the amount of memory for the namespace memory request in
        mebibytes (Mi)
      override:
        restrictedValues:
        - 1024Mi
        - 2048Mi
        - 4096Mi
        type: restricted
      required: true
    value: 1024Mi
    valueType: text
  - name: cpu
    options:
      description: Assign the amount of CPU for the namespace CPU request in milliCPU
        (m)
      override:
        restrictedValues:
        - 1000m
        - 2000m
        - 4000m
        type: restricted
      required: true
    value: 1000m
    valueType: text
  version: v1
  versionState: active
