apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: rafay-101-naas-andrew-naas
  project: andrew-naas
spec:
  envs:
  - key: RCTL_API_KEY
    value: UPDATE_VALUE
  - key: RCTL_API_SECRET
    value: UPDATE_VALUE
  - key: RCTL_REST_ENDPOINT
    value: UPDATE_VALUE
  - key: RCTL_PROJECT
    value: andrew-naas
